### ISSUE TITLE
E_USER_ERROR(256) - 1071: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by ghost** [Geeklog-Plugins/gus#4]
Hello DEvelopers,

I'm trying to install some plugins with the Geeklog 2.1.2 RC1. With this plugin I will be forwarded to the install URL in the plugin manager, but there is this error message.

```
E_USER_ERROR(256) - 1071: Specified key was too long; max key length is 1000 bytes @ /xxxxxxxxxxxxxx/system/databases/mysqli.class.php line 459
```

Could you see this again.

Thanks in advance.

Maybe the plugin needs to be fixed or updated.

P.S. I test the days very much at the Geeklog 2.1.2 RC 1 CMS.

**Comment by eSilverStrike** [comment]
Hi Alex,

This sounds like a plugin issue and MySQL database set to use UTF8mb4. I will take a look and add a fix (will not happen until next week)

**Comment by ghost** [comment]
Hi Tom,

Ok, yes i have UTF8mb4 collation in the database. Do you mean that I can get problems with other plugins during the installation?

I can not install the yesterday fixed Tag plugin and still the Paypal plugin. It is simply shown that there is an error in the installation.

Very bad and probably I could not have set the MySQL database on UTF8mb4.

Thank you for taking your time.

**Comment by eSilverStrike** [comment]
You potentially could as it has to do with how large of a selection of columns on the database the plugin requests. The exact error you got above indicates that the plugin selected to much information at once on a database with a collation that uses UTF8mb4.

As a temporary fix you could switch the collation of the database, tables and any columns back to just utf8_general_ci. (or just do it for the gus plugin)
